name: Lamp Deployment
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  linting:
    name: Lint Ansible Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linting
        uses: ansible/ansible-lint-action@main    
        with:
          targets: |
            ansible/*.yml
          path: "-c ../../ansible/.ansible-lint"
      - name: Publish Playbook Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: playbook
          path: ansible/
    

