name: Lamp Deployment
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  linting:
    name: Lint Ansible Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linting
        uses: ansible/ansible-lint-action@151b9a224f53c80fdc2c7aed08f3671d190e7a9e
        with:
          targets: |
            ../ansible/inventory.yml
          # args: "-c ansible/.ansible-lint"
    

