name: Lamp Deployment
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  linting:
    name: Lint Ansible Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linting
        uses: ansible/ansible-lint-action@151b9a2
        with:
          targets: |
            ansible/inventory.yml
          args: "-c ansible/.ansible-lint"
    

