name: Lamp Deployment
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  linting:
    name: Lint Ansible Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linting
        uses: ansible/ansible-lint-action@main    
        with:
          targets: |
            ansible/*.yml
          path: "-c ../../ansible/.ansible-lint"
      #  upload the playbook as an artifact
      - name: Publish Playbook Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: playbook
          path: ansible/
  deploy_to_test:
    name: Deploy to Test
    needs: linting
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    # start by downloading the artifact from the linting job
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: playbook
        path: ansible
    - uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: ansible
        options: |
          --inventory inventory-test.yml
          --extra-vars "test_ssh_password=${{Secrets.TEST_SSH_PASSWORD}}"
        
      
    
  
    
    

